MAX_NUMBER_OF_WAITING_CLIENTS = 5
SERVER_KEY_EXCHANGE__ADDRESS = "10.0.0.6"
SERVER_KEY_EXCHANGE__PORT = 12344

SERVER_AUDIO_RECEIPT__ADDRESS = "10.0.0.6"
SERVER_AUDIO_RECEIPT__PORT = 12348

AUDIO_MULTICAST__ADDRESS = "224.3.29.71"
AUDIO_MULTICAST__PORT = 10000
AUDIO_MULTICAST__SENDER_TIMEOUT = 0.2
# AUDIO_MULTICAST__RECEIVER_ADDRESS = "127.0.0.1"
AUDIO_MULTICAST__RECEIVER_ADDRESS = ''
AUDIO_MULTICAST__RECEIVER_PORT = AUDIO_MULTICAST__PORT
